---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/header.json
  label: Header
- type: document
  path: content/footer.json
  label: Footer
- type: document
  path: content/products.json
  label: Products
- type: document
  path: content/faqs.json
  label: FAQs
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*.json"
  new_doc_ext: ".json"
  templates:
  - page
- type: directory
  path: content/posts
  label: Blog posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: content/uploads
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
