---
label: Products
hide_body: true
fields:
- name: products
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: Name
  - name: description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  - name: pictures
    type: image_gallery
    config: {}
    label: Pictures
  - name: ingredients
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Ingredients
  config:
    min: 
    max: 
    labelField: 
  label: Products
